---
name: '🧨💥 Stop server...'
on:
  workflow_dispatch:

concurrency:
  group: server

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: eu-west-1
  INSTANCE_ID: i-01a48a932e24bbfb0

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Stop instance
        run: |
          aws ec2 stop-instances --instance-ids ${{ env.INSTANCE_ID }}
